name: "Post blog to hashnode"

on:
  push:
    branches: [ "main" ]
   
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          gh-token: ${{secrets.GITHUB_TOKEN}}
          hashnode-personal-access-token: ${{secrets.HASHNODE_PERSONAL_ACCESS_TOKEN}}
          # blog-custom-dir: "blogs"