name: "Post blog to hashnode"

on: pull_request
   
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            md:
              - '**/*.md'
      - uses: ./
        with:
          gh-token: ${{secrets.GITHUB_TOKEN}}
          hashnode-personal-access-token: ${{secrets.HASHNODE_PERSONAL_ACCESS_TOKEN}}
          # blog-custom-dir: "blogs"